"""UI string translations.

Only the interface is translated; app names/descriptions stay in the author's
language (like Flathub, GitHub, etc.). Language is chosen by the `lang` cookie,
falling back to the browser's Accept-Language, then Italian.

Coverage note: the high-traffic pages (nav, home, app page, login, categories)
are fully translated. Admin and publish are technical, low-traffic forms and
are left for a later pass; they fall back to Italian via the default.
"""
from __future__ import annotations

LANGS = {
    "it": "Italiano",
    "es": "Español",
    "de": "Deutsch",
    "zh": "中文",
    "nl": "Nederlands",
    "fr": "Français",
    "ja": "日本語",
    "vec": "Vèneto",
}

# Flag emoji per language, for the picker. If WebPositive lacks the emoji font,
# the language name shown next to it keeps the picker usable. Venetian is a
# region, not a nation: a lion emoji evokes the Lion of St Mark.
FLAGS = {
    "it": "🇮🇹", "es": "🇪🇸", "de": "🇩🇪", "zh": "🇨🇳",
    "nl": "🇳🇱", "fr": "🇫🇷", "ja": "🇯🇵", "vec": "🦁",
}

DEFAULT_LANG = "it"

# Note on "vec" (Venetian): it has no single codified spelling and many local
# variants; the strings below are a reasonable common rendering, not an official
# standard. `normalize_lang` keeps 3-letter codes like "vec" intact.

# key -> {lang: text}. Missing (lang, key) falls back to Italian, then the key.
STRINGS: dict[str, dict[str, str]] = {
    'nav.search_placeholder': {"it": "Cerca un'app per Haiku", "es": 'Busca una app para Haiku', "de": 'Eine App für Haiku suchen', "zh": '搜索 Haiku 应用', "nl": 'Zoek een app voor Haiku', "fr": 'Rechercher une app pour Haiku', "ja": 'Haiku 用アプリを検索', "vec": "Serca un'app par Haiku"},
    'nav.search': {"it": 'Cerca', "es": 'Buscar', "de": 'Suchen', "zh": '搜索', "nl": 'Zoeken', "fr": 'Rechercher', "ja": '検索', "vec": 'Serca'},
    'nav.categories': {"it": 'Categorie', "es": 'Categorías', "de": 'Kategorien', "zh": '分类', "nl": 'Categorieën', "fr": 'Catégories', "ja": 'カテゴリ', "vec": 'Categorie'},
    'nav.my_apps': {"it": 'Le mie app', "es": 'Mis apps', "de": 'Meine Apps', "zh": '我的应用', "nl": 'Mijn apps', "fr": 'Mes apps', "ja": 'マイアプリ', "vec": 'Le me app'},
    'nav.publish': {"it": 'Pubblica', "es": 'Publicar', "de": 'Veröffentlichen', "zh": '发布', "nl": 'Publiceren', "fr": 'Publier', "ja": '公開', "vec": 'Publica'},
    'nav.admin': {"it": 'Admin', "es": 'Admin', "de": 'Admin', "zh": '管理', "nl": 'Beheer', "fr": 'Admin', "ja": '管理', "vec": 'Aministrasion'},
    'nav.login': {"it": 'Accedi', "es": 'Acceder', "de": 'Anmelden', "zh": '登录', "nl": 'Inloggen', "fr": 'Se connecter', "ja": 'ログイン', "vec": 'Entra'},
    'nav.logout': {"it": 'Esci', "es": 'Salir', "de": 'Abmelden', "zh": '退出', "nl": 'Uitloggen', "fr": 'Se déconnecter', "ja": 'ログアウト', "vec": 'Va fora'},
    'footer.text': {"it": "spritz e' un catalogo che punta agli autori originali. E' additivo a HaikuPorts, non un'alternativa: quando un'app esiste anche li', spritz te lo dice e ti manda alla versione curata.", "es": 'spritz es un catálogo que apunta a los autores originales. Es aditivo a HaikuPorts, no una alternativa: cuando una app también existe allí, spritz te lo dice y te lleva a la versión curada.', "de": 'spritz ist ein Katalog, der auf die ursprünglichen Autoren verweist. Es ergänzt HaikuPorts, ist keine Alternative: wenn eine App auch dort existiert, sagt spritz es dir und verweist auf die gepflegte Version.', "zh": 'spritz 是一个指向原始作者的目录。它是 HaikuPorts 的补充，而非替代：当某个应用也存在于那里时，spritz 会告诉你并引导你使用经过维护的版本。', "nl": 'spritz is een catalogus die naar de oorspronkelijke auteurs verwijst. Het is aanvullend op HaikuPorts, geen alternatief: als een app daar ook bestaat, vertelt spritz het je en verwijst naar de verzorgde versie.', "fr": "spritz est un catalogue qui pointe vers les auteurs originaux. Il complète HaikuPorts, ce n'est pas une alternative : quand une app existe aussi là-bas, spritz vous le dit et vous oriente vers la version maintenue.", "ja": 'spritz は元の作者を指すカタログです。HaikuPorts の代替ではなく補完であり、アプリがそちらにも存在する場合は spritz がそれを伝え、整備された版へ案内します。', "vec": 'spritz xe un catalogo che punta ai autori orixinali. Xe zonta a HaikuPorts, mìa na alternativa: cuando che na app esiste anca là, spritz te lo dixe e te manda a la version curà.'},
    'home.hero_title': {"it": 'Il catalogo del software per Haiku', "es": 'El catálogo de software para Haiku', "de": 'Der Software-Katalog für Haiku', "zh": 'Haiku 软件目录', "nl": 'De softwarecatalogus voor Haiku', "fr": 'Le catalogue de logiciels pour Haiku', "ja": 'Haiku 向けソフトウェアカタログ', "vec": 'El catalogo del software par Haiku'},
    'home.hero_lead': {"it": "Trova app native, sempre dagli autori originali. spritz raccoglie le fonti che esistono gia' (release su GitHub, repository di terze parti, archivi storici) in un unico indice cercabile.", "es": 'Encuentra apps nativas, siempre de los autores originales. spritz reúne las fuentes que ya existen (releases en GitHub, repositorios de terceros, archivos históricos) en un único índice buscable.', "de": 'Finde native Apps, immer von den ursprünglichen Autoren. spritz sammelt bereits vorhandene Quellen (GitHub-Releases, Drittanbieter-Repositorys, historische Archive) in einem durchsuchbaren Index.', "zh": '查找原生应用，始终来自原始作者。spritz 将已经存在的来源（GitHub 发布、第三方仓库、历史归档）汇集到一个可搜索的索引中。', "nl": 'Vind native apps, altijd van de oorspronkelijke auteurs. spritz verzamelt bestaande bronnen (GitHub-releases, repositories van derden, historische archieven) in één doorzoekbare index.', "fr": 'Trouvez des apps natives, toujours des auteurs originaux. spritz rassemble les sources qui existent déjà (releases GitHub, dépôts tiers, archives historiques) dans un index unique consultable.', "ja": '常に元の作者からのネイティブアプリを見つけましょう。spritz は既存のソース（GitHub のリリース、サードパーティのリポジトリ、歴史的アーカイブ）を検索可能な単一のインデックスにまとめます。', "vec": 'Cata app native, senpre dai autori orixinali. spritz raccoglie le fonti che esiste xà (release su GitHub, repository de tersi, archivi storici) in un sol indice serchàbile.'},
    'home.search_placeholder': {"it": 'Es. Genio, editor, IDE', "es": 'Ej. Genio, editor, IDE', "de": 'z.B. Genio, Editor, IDE', "zh": '例如 Genio、编辑器、IDE', "nl": 'Bijv. Genio, editor, IDE', "fr": 'Ex. Genio, éditeur, IDE', "ja": '例: Genio、エディタ、IDE', "vec": 'Es. Genio, editor, IDE'},
    'home.browse': {"it": 'Sfoglia', "es": 'Explorar', "de": 'Durchsuchen', "zh": '浏览', "nl": 'Bladeren', "fr": 'Parcourir', "ja": '閲覧', "vec": 'Sfoja'},
    'home.results_for': {"it": 'Risultati per', "es": 'Resultados para', "de": 'Ergebnisse für', "zh": '搜索结果：', "nl": 'Resultaten voor', "fr": 'Résultats pour', "ja": '検索結果:', "vec": 'Resultati par'},
    'home.browse_by_category': {"it": 'sfoglia per categoria', "es": 'explorar por categoría', "de": 'nach Kategorie durchsuchen', "zh": '按分类浏览', "nl": 'bladeren per categorie', "fr": 'parcourir par catégorie', "ja": 'カテゴリで閲覧', "vec": 'sfoja par categoria'},
    'home.clear_filters': {"it": 'azzera i filtri', "es": 'borrar filtros', "de": 'Filter zurücksetzen', "zh": '清除筛选', "nl": 'filters wissen', "fr": 'réinitialiser les filtres', "ja": 'フィルタを解除', "vec": 'neta i filtri'},
    'home.no_results': {"it": 'Nessun risultato. Prova con un altro termine.', "es": 'Sin resultados. Prueba con otro término.', "de": 'Keine Ergebnisse. Versuche einen anderen Begriff.', "zh": '没有结果。请尝试其他关键词。', "nl": 'Geen resultaten. Probeer een andere term.', "fr": 'Aucun résultat. Essayez un autre terme.', "ja": '結果がありません。別の語句をお試しください。', "vec": "Nissun resultà. Prova co 'n altro termine."},
    'home.empty_catalog': {"it": "Il catalogo e' ancora vuoto.", "es": 'El catálogo aún está vacío.', "de": 'Der Katalog ist noch leer.', "zh": '目录还是空的。', "nl": 'De catalogus is nog leeg.', "fr": 'Le catalogue est encore vide.', "ja": 'カタログはまだ空です。', "vec": 'El catalogo xe ancora vodo.'},
    'home.prev': {"it": 'Precedente', "es": 'Anterior', "de": 'Zurück', "zh": '上一页', "nl": 'Vorige', "fr": 'Précédent', "ja": '前へ', "vec": 'Indrìo'},
    'home.next': {"it": 'Successiva', "es": 'Siguiente', "de": 'Weiter', "zh": '下一页', "nl": 'Volgende', "fr": 'Suivant', "ja": '次へ', "vec": 'Vanti'},
    'home.page_of': {"it": 'Pagina {p} di {n}', "es": 'Página {p} de {n}', "de": 'Seite {p} von {n}', "zh": '第 {p} 页，共 {n} 页', "nl": 'Pagina {p} van {n}', "fr": 'Page {p} sur {n}', "ja": '{n} ページ中 {p} ページ', "vec": 'Pagina {p} de {n}'},
    'home.apps_count': {"it": '{n} app', "es": '{n} apps', "de": '{n} Apps', "zh": '{n} 个应用', "nl": '{n} apps', "fr": '{n} apps', "ja": '{n} 個のアプリ', "vec": '{n} app'},
    'badge.also_on_hp': {"it": 'anche su HaikuPorts', "es": 'también en HaikuPorts', "de": 'auch in HaikuPorts', "zh": '也在 HaikuPorts 中', "nl": 'ook op HaikuPorts', "fr": 'aussi sur HaikuPorts', "ja": 'HaikuPorts にもあり', "vec": 'anca su HaikuPorts'},
    'cat.browse_title': {"it": 'Sfoglia per categoria', "es": 'Explorar por categoría', "de": 'Nach Kategorie durchsuchen', "zh": '按分类浏览', "nl": 'Bladeren per categorie', "fr": 'Parcourir par catégorie', "ja": 'カテゴリで閲覧', "vec": 'Sfoja par categoria'},
    'cat.back': {"it": 'torna al catalogo', "es": 'volver al catálogo', "de": 'zurück zum Katalog', "zh": '返回目录', "nl": 'terug naar de catalogus', "fr": 'retour au catalogue', "ja": 'カタログに戻る', "vec": 'torna al catalogo'},
    'cat.empty': {"it": 'Nessuna categoria ancora.', "es": 'Aún no hay categorías.', "de": 'Noch keine Kategorien.', "zh": '暂无分类。', "nl": 'Nog geen categorieën.', "fr": 'Aucune catégorie pour le moment.', "ja": 'カテゴリはまだありません。', "vec": 'Ancora nissuna categoria.'},
    'app.install': {"it": 'Installa', "es": 'Instalar', "de": 'Installieren', "zh": '安装', "nl": 'Installeren', "fr": 'Installer', "ja": 'インストール', "vec": 'Instala'},
    'app.channel': {"it": 'Canale', "es": 'Canal', "de": 'Kanal', "zh": '渠道', "nl": 'Kanaal', "fr": 'Canal', "ja": 'チャンネル', "vec": 'Canal'},
    'app.author': {"it": 'Autore', "es": 'Autor', "de": 'Autor', "zh": '作者', "nl": 'Auteur', "fr": 'Auteur', "ja": '作者', "vec": 'Autor'},
    'app.packager': {"it": 'Packager', "es": 'Empaquetador', "de": 'Packager', "zh": '打包者', "nl": 'Packager', "fr": 'Empaqueteur', "ja": 'パッケージャ', "vec": 'Inpachetador'},
    'app.site': {"it": 'Sito', "es": 'Sitio', "de": 'Webseite', "zh": '网站', "nl": 'Site', "fr": 'Site', "ja": 'サイト', "vec": 'Sito'},
    'app.license': {"it": 'Licenza', "es": 'Licencia', "de": 'Lizenz', "zh": '许可证', "nl": 'Licentie', "fr": 'Licence', "ja": 'ライセンス', "vec": 'Licensa'},
    'app.details': {"it": 'Dettagli', "es": 'Detalles', "de": 'Details', "zh": '详情', "nl": 'Details', "fr": 'Détails', "ja": '詳細', "vec": 'Detai'},
    'app.screenshots': {"it": 'Schermate', "es": 'Capturas', "de": 'Screenshots', "zh": '截图', "nl": 'Schermafbeeldingen', "fr": "Captures d'écran", "ja": 'スクリーンショット', "vec": 'Schermade'},
    'app.screenshots_hds': {"it": 'Schermate da HaikuDepotServer.', "es": 'Capturas de HaikuDepotServer.', "de": 'Screenshots von HaikuDepotServer.', "zh": '截图来自 HaikuDepotServer。', "nl": 'Schermafbeeldingen van HaikuDepotServer.', "fr": "Captures d'écran depuis HaikuDepotServer.", "ja": 'スクリーンショットは HaikuDepotServer より。', "vec": "Schermade da HaikuDepotServer."},
    'app.description': {"it": 'Descrizione', "es": 'Descripción', "de": 'Beschreibung', "zh": '描述', "nl": 'Beschrijving', "fr": 'Description', "ja": '説明', "vec": 'Descrission'},
    'app.description_hds': {"it": 'Descrizione da HaikuDepotServer.', "es": 'Descripción de HaikuDepotServer.', "de": 'Beschreibung von HaikuDepotServer.', "zh": '描述来自 HaikuDepotServer。', "nl": 'Beschrijving van HaikuDepotServer.', "fr": 'Description depuis HaikuDepotServer.', "ja": '説明は HaikuDepotServer より。', "vec": "Descrission da HaikuDepotServer."},
    'app.also_on_hp_title': {"it": 'Anche su HaikuPorts.', "es": 'También en HaikuPorts.', "de": 'Auch in HaikuPorts.', "zh": '也在 HaikuPorts 中。', "nl": 'Ook op HaikuPorts.', "fr": 'Aussi sur HaikuPorts.', "ja": 'HaikuPorts にもあります。', "vec": 'Anca su HaikuPorts.'},
    'app.add_repo': {"it": 'Aggiungi il repository in HaikuDepot', "es": 'Añade el repositorio en HaikuDepot', "de": 'Repository in HaikuDepot hinzufügen', "zh": '在 HaikuDepot 中添加该仓库', "nl": 'Voeg de repository toe in HaikuDepot', "fr": 'Ajouter le dépôt dans HaikuDepot', "ja": 'HaikuDepot にリポジトリを追加', "vec": 'Zonta el repository in HaikuDepot'},
    'app.from_haikuports': {"it": "Questa app e' curata in HaikuPorts. Installala da li', e' gia' disponibile in HaikuDepot.", "es": 'Esta app está curada en HaikuPorts. Instálala desde allí, ya está disponible en HaikuDepot.', "de": 'Diese App wird in HaikuPorts gepflegt. Installiere sie von dort, sie ist bereits in HaikuDepot verfügbar.', "zh": '此应用在 HaikuPorts 中维护。请从那里安装，它已在 HaikuDepot 中提供。', "nl": 'Deze app wordt onderhouden in HaikuPorts. Installeer hem daar, hij is al beschikbaar in HaikuDepot.', "fr": 'Cette app est maintenue dans HaikuPorts. Installez-la depuis là, elle est déjà disponible dans HaikuDepot.', "ja": 'このアプリは HaikuPorts で管理されています。そちらからインストールしてください。HaikuDepot で既に利用できます。', "vec": 'Sta app xe curà su HaikuPorts. Instalela da là, xe xà disponìbile in HaikuDepot.'},
    'app.add_repo_hint': {"it": 'Copia questo URL in HaikuDepot (Repository), poi installa {name} come qualsiasi altro pacchetto. Nessun client aggiuntivo richiesto.', "es": 'Copia esta URL en HaikuDepot (Repositorios), luego instala {name} como cualquier otro paquete. No hace falta ningún cliente adicional.', "de": 'Kopiere diese URL in HaikuDepot (Repositorys), dann installiere {name} wie jedes andere Paket. Kein zusätzlicher Client nötig.', "zh": '将此 URL 复制到 HaikuDepot（仓库），然后像安装其他软件包一样安装 {name}。无需额外客户端。', "nl": 'Kopieer deze URL naar HaikuDepot (Repositories) en installeer {name} als elk ander pakket. Geen extra client nodig.', "fr": 'Copiez cette URL dans HaikuDepot (Dépôts), puis installez {name} comme tout autre paquet. Aucun client supplémentaire requis.', "ja": 'この URL を HaikuDepot（リポジトリ）に貼り付け、他のパッケージと同じように {name} をインストールします。追加のクライアントは不要です。', "vec": 'Copia sto URL in HaikuDepot (Repository), po instala {name} come qualsiasi altro pacheto. Nissun client zontà richiesto.'},
    'app.repo_not_built': {"it": "Il repository per questo canale non e' ancora stato generato. Riprova piu' tardi, oppure usa il client spritz nativo.", "es": 'El repositorio para este canal aún no se ha generado. Inténtalo más tarde, o usa el cliente nativo de spritz.', "de": 'Das Repository für diesen Kanal wurde noch nicht erzeugt. Versuche es später erneut oder nutze den nativen spritz-Client.', "zh": '此渠道的仓库尚未生成。请稍后再试，或使用原生 spritz 客户端。', "nl": 'De repository voor dit kanaal is nog niet gegenereerd. Probeer het later opnieuw, of gebruik de native spritz-client.', "fr": "Le dépôt pour ce canal n'a pas encore été généré. Réessayez plus tard, ou utilisez le client spritz natif.", "ja": 'このチャンネルのリポジトリはまだ生成されていません。後でもう一度試すか、ネイティブの spritz クライアントを使ってください。', "vec": "El repository par sto canal no xe ancora stà generà. Prova pi tardi, o dopara el client spritz nativo."},
    'app.channel_follows': {"it": "Il canale {channel} segue l'ultima release dell'autore e richiede il client spritz nativo.", "es": 'El canal {channel} sigue la última versión del autor y requiere el cliente nativo de spritz.', "de": 'Der Kanal {channel} folgt der neuesten Veröffentlichung des Autors und benötigt den nativen spritz-Client.', "zh": '{channel} 渠道跟随作者的最新发布，需要原生 spritz 客户端。', "nl": 'Het kanaal {channel} volgt de nieuwste release van de auteur en vereist de native spritz-client.', "fr": "Le canal {channel} suit la dernière version de l'auteur et nécessite le client spritz natif.", "ja": '{channel} チャンネルは作者の最新リリースに追従し、ネイティブの spritz クライアントが必要です。', "vec": "El canal {channel} séguita l'ùltima release de l'autor e ghe vol el client spritz nativo."},
    'app.get_spritz_cta': {"it": 'Installa spritz per aggiornamenti automatici e installazione in un clic', "es": 'Instala spritz para actualizaciones automáticas e instalación con un clic', "de": 'Installiere spritz für automatische Updates und Ein-Klick-Installation', "zh": '安装 spritz 以获得自动更新和一键安装', "nl": 'Installeer spritz voor automatische updates en installatie met één klik', "fr": 'Installez spritz pour les mises à jour automatiques et l\'installation en un clic', "ja": '自動更新とワンクリックインストールのために spritz をインストール', "vec": 'Instala spritz par agiornamenti automàtici e instalasion in un click'},
    'login.title': {"it": 'Accedi', "es": 'Acceder', "de": 'Anmelden', "zh": '登录', "nl": 'Inloggen', "fr": 'Se connecter', "ja": 'ログイン', "vec": 'Entra'},
    'login.lead': {"it": 'Entra per gestire la tua libreria e pubblicare le tue app. Se non hai un account, registrane uno: basta una email e una password.', "es": 'Entra para gestionar tu biblioteca y publicar tus apps. Si no tienes cuenta, crea una: basta un email y una contraseña.', "de": 'Melde dich an, um deine Bibliothek zu verwalten und deine Apps zu veröffentlichen. Ohne Konto registriere eines: nur E-Mail und Passwort nötig.', "zh": '登录以管理你的库并发布你的应用。如果没有账户，注册一个即可：只需邮箱和密码。', "nl": 'Log in om je bibliotheek te beheren en je apps te publiceren. Geen account? Maak er een aan: alleen e-mail en wachtwoord nodig.', "fr": 'Connectez-vous pour gérer votre bibliothèque et publier vos apps. Sans compte, créez-en un : un email et un mot de passe suffisent.', "ja": 'ログインしてライブラリを管理し、アプリを公開しましょう。アカウントがなければ登録してください。メールとパスワードだけで済みます。', "vec": 'Entra par gestir la to libraria e publicar le to app. Se no ti ga un account, registrane uno: basta na email e na password.'},
    'login.email': {"it": 'Email', "es": 'Email', "de": 'E-Mail', "zh": '邮箱', "nl": 'E-mail', "fr": 'Email', "ja": 'メール', "vec": 'Email'},
    'login.password': {"it": 'Password', "es": 'Contraseña', "de": 'Passwort', "zh": '密码', "nl": 'Wachtwoord', "fr": 'Mot de passe', "ja": 'パスワード', "vec": 'Password'},
    'login.min_chars': {"it": 'Almeno {n} caratteri.', "es": 'Al menos {n} caracteres.', "de": 'Mindestens {n} Zeichen.', "zh": '至少 {n} 个字符。', "nl": 'Minstens {n} tekens.', "fr": 'Au moins {n} caractères.', "ja": '{n} 文字以上。', "vec": 'Almanco {n} caràteri.'},
    'login.register': {"it": 'Registrati', "es": 'Registrarse', "de": 'Registrieren', "zh": '注册', "nl": 'Registreren', "fr": "S'inscrire", "ja": '登録', "vec": 'Registrate'},
    'lang.label': {"it": 'Lingua', "es": 'Idioma', "de": 'Sprache', "zh": '语言', "nl": 'Taal', "fr": 'Langue', "ja": '言語', "vec": 'Lengua'},
    'lib.add': {"it": 'Aggiungi alla libreria', "es": 'Añadir a la biblioteca', "de": 'Zur Bibliothek hinzufügen', "zh": '添加到库', "nl": 'Aan bibliotheek toevoegen', "fr": 'Ajouter à la bibliothèque', "ja": 'ライブラリに追加', "vec": 'Zonta a la libraria'},
    'lib.login_first': {"it": 'Accedi per aggiungere alla libreria.', "es": 'Accede para añadir a la biblioteca.', "de": 'Anmelden, um zur Bibliothek hinzuzufügen.', "zh": '请登录以添加到库。', "nl": 'Log in om aan de bibliotheek toe te voegen.', "fr": 'Connectez-vous pour ajouter à la bibliothèque.', "ja": 'ライブラリに追加するにはログインしてください。', "vec": 'Entra par zontar a la libraria.'},
    'lib.added': {"it": 'Aggiunta alla libreria.', "es": 'Añadida a la biblioteca.', "de": 'Zur Bibliothek hinzugefügt.', "zh": '已添加到库。', "nl": 'Toegevoegd aan bibliotheek.', "fr": 'Ajoutée à la bibliothèque.', "ja": 'ライブラリに追加しました。', "vec": 'Zontà a la libraria.'},
    'lib.error': {"it": 'Errore.', "es": 'Error.', "de": 'Fehler.', "zh": '错误。', "nl": 'Fout.', "fr": 'Erreur.', "ja": 'エラー。', "vec": 'Eror.'},
    'lib.remove': {"it": 'Rimuovi', "es": 'Quitar', "de": 'Entfernen', "zh": '移除', "nl": 'Verwijderen', "fr": 'Retirer', "ja": '削除', "vec": 'Cava via'},
    'lib.state.pending': {"it": 'in coda', "es": 'en cola', "de": 'in Warteschlange', "zh": '队列中', "nl": 'in wachtrij', "fr": "en file d'attente", "ja": '待機中', "vec": 'in coa'},
    'lib.state.installed': {"it": 'installata', "es": 'instalada', "de": 'installiert', "zh": '已安装', "nl": 'geïnstalleerd', "fr": 'installée', "ja": 'インストール済み', "vec": 'instalà'},
    'lib.state.removed': {"it": 'rimossa', "es": 'quitada', "de": 'entfernt', "zh": '已移除', "nl": 'verwijderd', "fr": 'retirée', "ja": '削除済み', "vec": 'cavà via'},
    'e404.title': {"it": 'Pagina non trovata', "es": 'Página no encontrada', "de": 'Seite nicht gefunden', "zh": '页面未找到', "nl": 'Pagina niet gevonden', "fr": 'Page introuvable', "ja": 'ページが見つかりません', "vec": 'Pagina mìa catà'},
    'e404.lead': {"it": "Questa pagina non c'e' (o non c'e' piu'). Capita.", "es": 'Esta página no existe (o ya no existe). Pasa.', "de": 'Diese Seite gibt es nicht (mehr). Kommt vor.', "zh": '此页面不存在（或已不存在）。这种事会发生。', "nl": 'Deze pagina bestaat niet (meer). Gebeurt.', "fr": "Cette page n'existe pas (ou plus). Ça arrive.", "ja": 'このページはありません（もうない）。よくあることです。', "vec": "Sta pagina no ghe xe (o no ghe xe pi). Capita."},
    'e404.osdrawer': {"it": 'Come OSDrawer, uno dei posti dove giravano i programmi per BeOS e Haiku, chiuso ormai da anni. Le cose spariscono dal web: spritz prova a tenerne traccia.', "es": 'Como OSDrawer, uno de los sitios donde circulaban los programas para BeOS y Haiku, cerrado hace años. Las cosas desaparecen de la web: spritz intenta no perderles el rastro.', "de": 'Wie OSDrawer, einer der Orte für BeOS- und Haiku-Programme, seit Jahren geschlossen. Dinge verschwinden aus dem Web: spritz versucht, den Überblick zu behalten.', "zh": '就像 OSDrawer，曾经分发 BeOS 和 Haiku 程序的地方之一，多年前已关闭。东西会从网上消失：spritz 试着把它们留住。', "nl": 'Zoals OSDrawer, ooit een plek voor BeOS- en Haiku-programma\'s, al jaren dicht. Dingen verdwijnen van het web: spritz probeert ze bij te houden.', "fr": 'Comme OSDrawer, un des endroits où circulaient les programmes BeOS et Haiku, fermé depuis des années. Les choses disparaissent du web : spritz essaie d\'en garder la trace.', "ja": 'かつて BeOS や Haiku のプログラムが集まった場所のひとつ OSDrawer のように、もう何年も前に閉じました。ウェブから物事は消えていきます。spritz はそれを追い続けようとしています。', "vec": 'Come OSDrawer, uno dei posti indove che girava i programi par BeOS e Haiku, sarà da ani. Le robe sparisse dal web: spritz prova a tegnerghe drìo.'},
    'e404.home': {"it": 'Torna al catalogo', "es": 'Volver al catálogo', "de": 'Zum Katalog', "zh": '返回目录', "nl": 'Naar de catalogus', "fr": 'Retour au catalogue', "ja": 'カタログへ', "vec": 'Torna al catalogo'},
    'home.curated_note': {"it": 'In evidenza le app dalle fonti di terze parti, quelle che HaikuDepot non mostra. Cerca per trovare tutto, HaikuPorts incluso.', "es": 'Destacamos las apps de fuentes de terceros, las que HaikuDepot no muestra. Busca para encontrar todo, incluido HaikuPorts.', "de": 'Hervorgehoben: Apps aus Drittanbieter-Quellen, die HaikuDepot nicht zeigt. Suche, um alles zu finden, auch HaikuPorts.', "zh": '突出显示第三方来源的应用，即 HaikuDepot 不显示的那些。搜索可找到全部，包括 HaikuPorts。', "nl": 'Uitgelicht: apps van externe bronnen die HaikuDepot niet toont. Zoek om alles te vinden, inclusief HaikuPorts.', "fr": 'En avant : les apps de sources tierces, celles que HaikuDepot ne montre pas. Cherchez pour tout trouver, HaikuPorts compris.', "ja": 'HaikuDepot に表示されないサードパーティ製アプリを強調表示。検索すれば HaikuPorts を含むすべてが見つかります。', "vec": "In evidensa le app da le fonti de tersi, quee che HaikuDepot no mostra. Serca par catar tuto, anca HaikuPorts."},
    'home.featured': {"it": 'App in evidenza', "es": 'App destacada', "de": 'Empfohlene App', "zh": '精选应用', "nl": 'Uitgelichte app', "fr": 'App en vedette', "ja": '注目のアプリ', "vec": "App in evidensa"},
    'home.featured_cta': {"it": 'Scopri', "es": 'Descubrir', "de": 'Entdecken', "zh": '查看', "nl": 'Ontdek', "fr": 'Découvrir', "ja": '見る', "vec": "Varda"},
    'home.top_month': {"it": 'Più scaricati questo mese', "es": 'Más descargadas este mes', "de": 'Meistgeladen diesen Monat', "zh": '本月下载最多', "nl": 'Meest gedownload deze maand', "fr": 'Les plus téléchargées ce mois-ci', "ja": '今月のダウンロード数上位', "vec": "Pi scargà 'sto mese"},
    'home.from_repos': {"it": 'Dai repository', "es": 'De los repositorios', "de": 'Aus den Repositorys', "zh": '来自仓库', "nl": 'Uit de repositories', "fr": 'Depuis les dépôts', "ja": 'リポジトリから', "vec": "Dai repository"},
    'home.downloads_title': {"it": 'Download registrati questo mese', "es": 'Descargas registradas este mes', "de": 'Erfasste Downloads diesen Monat', "zh": '本月记录的下载次数', "nl": 'Geregistreerde downloads deze maand', "fr": 'Téléchargements enregistrés ce mois-ci', "ja": '今月の記録されたダウンロード数', "vec": "Download registrà 'sto mese"},
    'home.all_catalog': {"it": 'Tutto il catalogo', "es": 'Todo el catálogo', "de": 'Gesamter Katalog', "zh": '全部目录', "nl": 'Hele catalogus', "fr": 'Tout le catalogue', "ja": 'カタログ全体', "vec": "Tuto el catalogo"},
    'card.in_repos': {"it": 'in {n} repository', "es": 'en {n} repositorios', "de": 'in {n} Repositorys', "zh": '在 {n} 个仓库中', "nl": 'in {n} repositories', "fr": 'dans {n} dépôts', "ja": '{n} 個のリポジトリに', "vec": "in {n} repository"},
    'app.also_in': {"it": 'Disponibile anche in', "es": 'Disponible también en', "de": 'Auch verfügbar in', "zh": '也可在以下位置获取', "nl": 'Ook beschikbaar in', "fr": 'Aussi disponible dans', "ja": '他の入手先', "vec": "Disponibie anca in"},
    'app.also_in_hint': {"it": 'La stessa app è pubblicata in più repository. spritz non sceglie per te: qui sotto le fonti, con la versione più recente evidenziata. Scegli quella che preferisci.', "es": 'La misma app está publicada en varios repositorios. spritz no elige por ti: aquí están las fuentes, con la versión más reciente resaltada. Elige la que prefieras.', "de": 'Dieselbe App ist in mehreren Repositorys veröffentlicht. spritz wählt nicht für dich: hier die Quellen, die neueste Version ist hervorgehoben. Wähle deine bevorzugte.', "zh": '同一应用发布在多个仓库中。spritz 不替你选择：以下是来源，已标出最新版本。请选择你偏好的。', "nl": 'Dezelfde app staat in meerdere repositories. spritz kiest niet voor je: hieronder de bronnen, met de nieuwste versie gemarkeerd. Kies je voorkeur.', "fr": 'La même app est publiée dans plusieurs dépôts. spritz ne choisit pas à votre place : voici les sources, la version la plus récente est mise en avant. Choisissez la vôtre.', "ja": '同じアプリが複数のリポジトリで公開されています。spritz は選びません。最新バージョンを強調した入手先から選んでください。', "vec": "La stessa app xe publicà in pi repository. spritz no sielze par ti: qua soto le fonti, co la version pi recente evidensià. Sielzi quea che te piase."},
    'app.newest': {"it": 'più recente', "es": 'más reciente', "de": 'neueste', "zh": '最新', "nl": 'nieuwste', "fr": 'plus récente', "ja": '最新', "vec": "pi recente"},
    'app.latest_elsewhere': {"it": 'Una versione più recente è disponibile in un altro repository (evidenziata sotto).', "es": 'Hay una versión más reciente en otro repositorio (resaltada abajo).', "de": 'Eine neuere Version ist in einem anderen Repository verfügbar (unten hervorgehoben).', "zh": '另一个仓库中有更新的版本（下方已标出）。', "nl": 'Een nieuwere versie is beschikbaar in een ander repository (hieronder gemarkeerd).', "fr": 'Une version plus récente est disponible dans un autre dépôt (mise en avant ci-dessous).', "ja": '別のリポジトリに新しいバージョンがあります（下に強調表示）。', "vec": "Na version pi recente xe disponibie in un altro repository (evidensià qua soto)."},
    'app.latest_here': {"it": 'Questa è la versione più recente tra i repository disponibili.', "es": 'Esta es la versión más reciente entre los repositorios disponibles.', "de": 'Dies ist die neueste Version unter den verfügbaren Repositorys.', "zh": '这是可用仓库中的最新版本。', "nl": 'Dit is de nieuwste versie onder de beschikbare repositories.', "fr": 'Ceci est la version la plus récente parmi les dépôts disponibles.', "ja": 'これは利用可能なリポジトリの中で最新のバージョンです。', "vec": "Questa xe la version pi recente tra i repository disponibii."},
    # get spritz (the native client page, linked from every app's install CTA)
    'get.title': {"it": 'Il client spritz', "es": 'El cliente spritz', "de": 'Der spritz-Client', "zh": 'spritz 客户端', "nl": 'De spritz-client', "fr": 'Le client spritz', "ja": 'spritz クライアント', "vec": 'El client spritz'},
    'get.lead': {"it": "Il client nativo per Haiku è in lavorazione. Quando sarà pronto, gestirà i link spritz://, seguirà l'ultima release degli autori (canale ombra) e installerà con un clic dal browser.", "es": 'El cliente nativo para Haiku está en desarrollo. Cuando esté listo, gestionará los enlaces spritz://, seguirá la última versión de los autores (canal ombra) e instalará con un clic desde el navegador.', "de": 'Der native Haiku-Client ist in Arbeit. Sobald er fertig ist, verarbeitet er spritz://-Links, folgt der neuesten Veröffentlichung der Autoren (ombra-Kanal) und installiert mit einem Klick aus dem Browser.', "zh": '原生 Haiku 客户端正在开发中。完成后，它将处理 spritz:// 链接，跟随作者的最新发布（ombra 渠道），并从浏览器一键安装。', "nl": 'De native Haiku-client is in ontwikkeling. Zodra hij klaar is, verwerkt hij spritz://-links, volgt de nieuwste release van auteurs (ombra-kanaal) en installeert met één klik vanuit de browser.', "fr": "Le client natif pour Haiku est en cours de développement. Une fois prêt, il gérera les liens spritz://, suivra la dernière version des auteurs (canal ombra) et installera en un clic depuis le navigateur.", "ja": "Haiku ネイティブクライアントは開発中です。完成すると spritz:// リンクを処理し、作者の最新リリース（ombra チャンネル）に追従し、ブラウザからワンクリックでインストールします。", "vec": "El client nativo par Haiku xe in lavorasion. Co'l sarà pronto, el gestirà i link spritz://, el seguirà l'ùltima release dei autori (canal ombra) e el instalerà con un click dal browser."},
    'get.for_now': {"it": 'Per ora', "es": 'Por ahora', "de": 'Vorerst', "zh": '目前', "nl": 'Voorlopig', "fr": 'Pour l\'instant', "ja": '今のところ', "vec": 'Par deso'},
    'get.for_now_body': {"it": 'puoi aggiungere il repository stabile in HaikuDepot dalla pagina di ogni app: funziona da subito, senza nessun client aggiuntivo.', "es": 'puedes añadir el repositorio estable en HaikuDepot desde la página de cada app: funciona de inmediato, sin ningún cliente adicional.', "de": 'kannst du das stabile Repository in HaikuDepot von der Seite jeder App hinzufügen: es funktioniert sofort, ohne zusätzlichen Client.', "zh": '你可以从每个应用的页面在 HaikuDepot 中添加稳定仓库：立即可用，无需额外客户端。', "nl": 'kun je de stabiele repository in HaikuDepot toevoegen vanaf de pagina van elke app: werkt meteen, zonder extra client.', "fr": "vous pouvez ajouter le dépôt stable dans HaikuDepot depuis la page de chaque app : ça marche tout de suite, sans client supplémentaire.", "ja": "各アプリのページから HaikuDepot に安定版リポジトリを追加できます。追加のクライアントなしですぐに使えます。", "vec": "te pol zontar el repository stabie in HaikuDepot da la pagina de ogni app: el funsiona subito, sensa nissun client zontà."},
    'app.back_to_catalog': {"it": 'Torna al catalogo', "es": 'Volver al catálogo', "de": 'Zurück zum Katalog', "zh": '返回目录', "nl": 'Terug naar de catalogus', "fr": 'Retour au catalogue', "ja": 'カタログへ戻る', "vec": 'Torna al catalogo'},
    'app.install_oneclick': {"it": 'Installa con un clic (client spritz)', "es": 'Instalar con un clic (cliente spritz)', "de": 'Mit einem Klick installieren (spritz-Client)', "zh": '一键安装（spritz 客户端）', "nl": 'Installeren met één klik (spritz-client)', "fr": 'Installer en un clic (client spritz)', "ja": 'ワンクリックでインストール（spritz クライアント）', "vec": 'Instala con un click (client spritz)'},
    # library page
    'lib.page_lead': {"it": "Le app che hai messo in libreria. Quando il client spritz nativo è attivo, le installa e ne aggiorna lo stato (in coda, installata).", "es": 'Las apps que has puesto en tu biblioteca. Cuando el cliente nativo de spritz está activo, las instala y actualiza su estado (en cola, instalada).', "de": 'Die Apps in deiner Bibliothek. Wenn der native spritz-Client aktiv ist, installiert er sie und aktualisiert ihren Status (in Warteschlange, installiert).', "zh": '你放入库中的应用。原生 spritz 客户端启用后，会安装它们并更新状态（排队中、已安装）。', "nl": 'De apps in je bibliotheek. Wanneer de native spritz-client actief is, installeert hij ze en werkt de status bij (in wachtrij, geïnstalleerd).', "fr": "Les apps que vous avez mises en bibliothèque. Quand le client spritz natif est actif, il les installe et met à jour leur état (en file, installée).", "ja": "ライブラリに追加したアプリ。ネイティブ spritz クライアントが有効になると、インストールして状態（キュー内、インストール済み）を更新します。", "vec": "Le app che te ghè metù in libraria. Co'l client spritz nativo xe ativo, le instala e le agiorna el stato (in coa, instalà)."},
    'lib.login_heading': {"it": 'Accedi', "es": 'Acceder', "de": 'Anmelden', "zh": '登录', "nl": 'Inloggen', "fr": 'Se connecter', "ja": 'ログイン', "vec": 'Entra'},
    'lib.login_hint': {"it": 'Se hai fatto login, la tua libreria si carica da sola.', "es": 'Si has iniciado sesión, tu biblioteca se carga sola.', "de": 'Wenn du angemeldet bist, lädt deine Bibliothek von selbst.', "zh": '如果你已登录，你的库会自动加载。', "nl": 'Als je bent ingelogd, laadt je bibliotheek vanzelf.', "fr": 'Si vous êtes connecté, votre bibliothèque se charge toute seule.', "ja": 'ログイン済みなら、ライブラリは自動で読み込まれます。', "vec": 'Se te ghè fato login, la to libraria se carga da sola.'},
    'lib.token_placeholder': {"it": 'token di accesso', "es": 'token de acceso', "de": 'Zugriffstoken', "zh": '访问令牌', "nl": 'toegangstoken', "fr": "jeton d'accès", "ja": 'アクセストークン', "vec": 'token de aceso'},
    'lib.show_button': {"it": 'Mostra le mie app', "es": 'Mostrar mis apps', "de": 'Meine Apps zeigen', "zh": '显示我的应用', "nl": 'Toon mijn apps', "fr": 'Afficher mes apps', "ja": 'マイアプリを表示', "vec": 'Mostra le me app'},
    'lib.empty': {"it": "La tua libreria è vuota. Sfoglia il catalogo e aggiungi un'app.", "es": 'Tu biblioteca está vacía. Explora el catálogo y añade una app.', "de": 'Deine Bibliothek ist leer. Durchstöbere den Katalog und füge eine App hinzu.', "zh": '你的库是空的。浏览目录并添加一个应用。', "nl": 'Je bibliotheek is leeg. Blader door de catalogus en voeg een app toe.', "fr": "Votre bibliothèque est vide. Parcourez le catalogue et ajoutez une app.", "ja": "ライブラリは空です。カタログを見てアプリを追加してください。", "vec": "La to libraria xe voda. Varda el catalogo e zonta na app."},
    # login JS messages (passed to login.js via data-*)
    'login.required': {"it": 'Email e password sono obbligatorie.', "es": 'El email y la contraseña son obligatorios.', "de": 'E-Mail und Passwort sind erforderlich.', "zh": '电子邮件和密码为必填项。', "nl": 'E-mail en wachtwoord zijn verplicht.', "fr": "L'email et le mot de passe sont obligatoires.", "ja": 'メールとパスワードは必須です。', "vec": 'Email e password xe obligatori.'},
    'login.wait': {"it": 'Attendere...', "es": 'Espere...', "de": 'Bitte warten...', "zh": '请稍候...', "nl": 'Even wachten...', "fr": 'Veuillez patienter...', "ja": 'お待ちください...', "vec": 'Speta...'},
    'login.done': {"it": 'Fatto.', "es": 'Hecho.', "de": 'Fertig.', "zh": '完成。', "nl": 'Klaar.', "fr": 'Terminé.', "ja": '完了。', "vec": 'Fato.'},
    'login.wrong': {"it": 'Email o password errati.', "es": 'Email o contraseña incorrectos.', "de": 'E-Mail oder Passwort falsch.', "zh": '电子邮件或密码错误。', "nl": 'E-mail of wachtwoord onjuist.', "fr": 'Email ou mot de passe incorrect.', "ja": 'メールまたはパスワードが違います。', "vec": 'Email o password sbaglià.'},
    'login.exists': {"it": 'Questa email è già registrata. Prova ad accedere.', "es": 'Este email ya está registrado. Intenta acceder.', "de": 'Diese E-Mail ist bereits registriert. Versuche dich anzumelden.', "zh": '此电子邮件已注册。请尝试登录。', "nl": 'Dit e-mailadres is al geregistreerd. Probeer in te loggen.', "fr": 'Cet email est déjà enregistré. Essayez de vous connecter.', "ja": 'このメールは既に登録されています。ログインしてください。', "vec": 'Sta email xe za registrà. Prova a entrar.'},
    'login.short': {"it": 'Password troppo corta.', "es": 'Contraseña demasiado corta.', "de": 'Passwort zu kurz.', "zh": '密码太短。', "nl": 'Wachtwoord te kort.', "fr": 'Mot de passe trop court.', "ja": 'パスワードが短すぎます。', "vec": 'Password massa curta.'},
    'login.throttled': {"it": 'Troppi tentativi, riprova tra poco.', "es": 'Demasiados intentos, inténtalo de nuevo pronto.', "de": 'Zu viele Versuche, versuche es bald erneut.', "zh": '尝试次数过多，请稍后再试。', "nl": 'Te veel pogingen, probeer het straks opnieuw.', "fr": 'Trop de tentatives, réessayez bientôt.', "ja": '試行回数が多すぎます。しばらくして再試行してください。', "vec": 'Massa tentativi, riprova tra un poco.'},
    'login.error': {"it": 'Errore.', "es": 'Error.', "de": 'Fehler.', "zh": '错误。', "nl": 'Fout.', "fr": 'Erreur.', "ja": 'エラー。', "vec": 'Eror.'},
    # library JS messages
    'lib.login_first': {"it": 'Accedi prima (link Accedi in alto).', "es": 'Inicia sesión primero (enlace Acceder arriba).', "de": 'Melde dich zuerst an (Link oben).', "zh": '请先登录（顶部的登录链接）。', "nl": 'Log eerst in (link bovenaan).', "fr": "Connectez-vous d'abord (lien en haut).", "ja": '先にログインしてください（上部のリンク）。', "vec": 'Entra prima (link Entra in alto).'},
    'lib.bad_token': {"it": 'Token non valido o scaduto.', "es": 'Token no válido o caducado.', "de": 'Token ungültig oder abgelaufen.', "zh": '令牌无效或已过期。', "nl": 'Token ongeldig of verlopen.', "fr": 'Jeton invalide ou expiré.', "ja": 'トークンが無効または期限切れです。', "vec": 'Token no vàlido o scadù.'},
    'lib.session_expired': {"it": 'Sessione scaduta, riaccedi.', "es": 'Sesión caducada, vuelve a acceder.', "de": 'Sitzung abgelaufen, melde dich erneut an.', "zh": '会话已过期，请重新登录。', "nl": 'Sessie verlopen, log opnieuw in.', "fr": 'Session expirée, reconnectez-vous.', "ja": 'セッションが切れました。再度ログインしてください。', "vec": 'Sesion scadùa, torna a entrar.'},
    'lib.error': {"it": 'Errore.', "es": 'Error.', "de": 'Fehler.', "zh": '错误。', "nl": 'Fout.', "fr": 'Erreur.', "ja": 'エラー。', "vec": 'Eror.'},
    # admin JS messages (passed to admin.js via data-* on #js-msgs)
    'adm.need': {"it": 'Accedi come admin, oppure incolla il token admin.', "es": 'Accede como admin, o pega el token de admin.', "de": 'Melde dich als Admin an oder füge den Admin-Token ein.', "zh": '请以管理员身份登录，或粘贴管理员令牌。', "nl": 'Log in als admin, of plak het admin-token.', "fr": "Connectez-vous en tant qu'admin, ou collez le jeton admin.", "ja": '管理者としてログインするか、管理者トークンを貼り付けてください。', "vec": 'Entra come admin, o incola el token admin.'},
    'adm.bad_token': {"it": 'Token admin non valido.', "es": 'Token de admin no válido.', "de": 'Admin-Token ungültig.', "zh": '管理员令牌无效。', "nl": 'Admin-token ongeldig.', "fr": 'Jeton admin invalide.', "ja": '管理者トークンが無効です。', "vec": 'Token admin no vàlido.'},
    'adm.disabled': {"it": 'Endpoint admin disabilitato (SPRITZ_ADMIN_TOKEN non configurato).', "es": 'Endpoint de admin deshabilitado (SPRITZ_ADMIN_TOKEN no configurado).', "de": 'Admin-Endpunkt deaktiviert (SPRITZ_ADMIN_TOKEN nicht gesetzt).', "zh": '管理员端点已禁用（未配置 SPRITZ_ADMIN_TOKEN）。', "nl": 'Admin-endpoint uitgeschakeld (SPRITZ_ADMIN_TOKEN niet ingesteld).', "fr": 'Endpoint admin désactivé (SPRITZ_ADMIN_TOKEN non configuré).', "ja": '管理者エンドポイントは無効です（SPRITZ_ADMIN_TOKEN 未設定）。', "vec": 'Endpoint admin disabilità (SPRITZ_ADMIN_TOKEN no configurà).'},
    'adm.error': {"it": 'Errore', "es": 'Error', "de": 'Fehler', "zh": '错误', "nl": 'Fout', "fr": 'Erreur', "ja": 'エラー', "vec": 'Eror'},
    'adm.need_url_slug': {"it": 'URL e slug sono obbligatori.', "es": 'La URL y el slug son obligatorios.', "de": 'URL und Slug sind erforderlich.', "zh": 'URL 和 slug 为必填项。', "nl": 'URL en slug zijn verplicht.', "fr": "L'URL et le slug sont obligatoires.", "ja": 'URL と slug は必須です。', "vec": 'URL e slug xe obligatori.'},
    'adm.ingesting': {"it": 'Ingest in corso...', "es": 'Ingest en curso...', "de": 'Ingest läuft...', "zh": '正在导入...', "nl": 'Ingest bezig...', "fr": 'Ingestion en cours...', "ja": 'インジェスト中...', "vec": 'Ingest in corso...'},
    'adm.done': {"it": 'Fatto.', "es": 'Hecho.', "de": 'Fertig.', "zh": '完成。', "nl": 'Klaar.', "fr": 'Terminé.', "ja": '完了。', "vec": 'Fato.'},
    'adm.importing': {"it": 'Import in corso (puo richiedere qualche secondo)...', "es": 'Importación en curso (puede tardar unos segundos)...', "de": 'Import läuft (kann ein paar Sekunden dauern)...', "zh": '正在导入（可能需要几秒钟）...', "nl": 'Import bezig (kan enkele seconden duren)...', "fr": "Import en cours (peut prendre quelques secondes)...", "ja": 'インポート中（数秒かかる場合があります）...', "vec": 'Import in corso (pol volerghe qualche secondo)...'},
    'adm.imported': {"it": 'Importati {n} di {found} pacchetti.', "es": 'Importados {n} de {found} paquetes.', "de": '{n} von {found} Paketen importiert.', "zh": '已导入 {found} 个中的 {n} 个包。', "nl": '{n} van {found} pakketten geïmporteerd.', "fr": '{n} sur {found} paquets importés.', "ja": '{found} 個中 {n} 個のパッケージをインポートしました。', "vec": 'Importà {n} de {found} pacheti.'},
    'adm.rebuilding': {"it": 'Rebuild in corso...', "es": 'Rebuild en curso...', "de": 'Rebuild läuft...', "zh": '正在重建...', "nl": 'Rebuild bezig...', "fr": 'Reconstruction en cours...', "ja": '再構築中...', "vec": 'Rebuild in corso...'},
    'adm.rebuilt': {"it": 'Rebuild: {n} repo, {e} errori.', "es": 'Rebuild: {n} repos, {e} errores.', "de": 'Rebuild: {n} Repos, {e} Fehler.', "zh": '重建：{n} 个仓库，{e} 个错误。', "nl": 'Rebuild: {n} repos, {e} fouten.', "fr": 'Reconstruction : {n} repos, {e} erreurs.', "ja": '再構築：{n} リポジトリ、{e} 件のエラー。', "vec": 'Rebuild: {n} repo, {e} erori.'},
    'adm.crawling': {"it": 'Prefetch ombra in corso...', "es": 'Prefetch ombra en curso...', "de": 'ombra-Prefetch läuft...', "zh": '正在预取 ombra...', "nl": 'ombra-prefetch bezig...', "fr": 'Préchargement ombra en cours...', "ja": 'ombra のプリフェッチ中...', "vec": 'Prefetch ombra in corso...'},
    'adm.crawled': {"it": 'Prefetch ombra: {n} app, {r} risolte, {e} errori.', "es": 'Prefetch ombra: {n} apps, {r} resueltas, {e} errores.', "de": 'ombra-Prefetch: {n} Apps, {r} aufgelöst, {e} Fehler.', "zh": 'ombra 预取：{n} 个应用，{r} 个已解析，{e} 个错误。', "nl": 'ombra-prefetch: {n} apps, {r} opgelost, {e} fouten.', "fr": 'Préchargement ombra : {n} apps, {r} résolues, {e} erreurs.', "ja": 'ombra プリフェッチ：{n} 個のアプリ、{r} 件解決、{e} 件エラー。', "vec": 'Prefetch ombra: {n} app, {r} resolte, {e} erori.'},
    'adm.recrawl': {"it": 'Ri-crawl', "es": 'Re-crawl', "de": 'Neu crawlen', "zh": '重新爬取', "nl": 'Opnieuw crawlen', "fr": 'Re-crawler', "ja": '再クロール', "vec": 'Ri-crawl'},
    'adm.delete': {"it": 'Elimina', "es": 'Eliminar', "de": 'Löschen', "zh": '删除', "nl": 'Verwijderen', "fr": 'Supprimer', "ja": '削除', "vec": 'Elimina'},
    'adm.confirm_delete': {"it": "Eliminare il bacaro '{slug}' e tutte le sue app dal catalogo?", "es": "¿Eliminar el bacaro '{slug}' y todas sus apps del catálogo?", "de": "Bacaro '{slug}' und alle seine Apps aus dem Katalog löschen?", "zh": "从目录中删除 bacaro '{slug}' 及其所有应用？", "nl": "Bacaro '{slug}' en al zijn apps uit de catalogus verwijderen?", "fr": "Supprimer le bacaro '{slug}' et toutes ses apps du catalogue ?", "ja": "bacaro '{slug}' とそのすべてのアプリをカタログから削除しますか？", "vec": "Eliminar el bacaro '{slug}' e tute le so app dal catalogo?"},
    'adm.deleting': {"it": 'Eliminazione...', "es": 'Eliminando...', "de": 'Wird gelöscht...', "zh": '正在删除...', "nl": 'Verwijderen...', "fr": 'Suppression...', "ja": '削除中...', "vec": 'Eliminazion...'},
    'adm.deleted': {"it": "Eliminato '{slug}' ({n} app rimosse).", "es": "Eliminado '{slug}' ({n} apps eliminadas).", "de": "'{slug}' gelöscht ({n} Apps entfernt).", "zh": "已删除 '{slug}'（移除了 {n} 个应用）。", "nl": "'{slug}' verwijderd ({n} apps verwijderd).", "fr": "'{slug}' supprimé ({n} apps retirées).", "ja": "'{slug}' を削除しました（{n} 個のアプリを削除）。", "vec": "Eliminà '{slug}' ({n} app rimosse)."},
    'adm.no_url': {"it": 'URL non memorizzato', "es": 'URL no almacenada', "de": 'URL nicht gespeichert', "zh": '未存储 URL', "nl": 'URL niet opgeslagen', "fr": 'URL non mémorisée', "ja": 'URL が保存されていません', "vec": 'URL no memorizà'},
    'adm.last_error': {"it": 'Ultimo errore:', "es": 'Último error:', "de": 'Letzter Fehler:', "zh": '最近错误：', "nl": 'Laatste fout:', "fr": 'Dernière erreur :', "ja": '最後のエラー：', "vec": 'Ultimo eror:'},
    'adm.confirm_delete_note': {"it": 'Il repo originale non viene toccato.', "es": 'El repo original no se toca.', "de": 'Das ursprüngliche Repo bleibt unberührt.', "zh": '不会触及原始仓库。', "nl": 'De originele repo blijft ongemoeid.', "fr": "Le repo d'origine n'est pas touché.", "ja": '元のリポジトリには触れません。', "vec": 'El repo original no vien tocà.'},
    # publish JS messages (passed to publish.js via data-* on #js-msgs)
    'pub.need_token': {"it": 'Incolla prima il tuo token di accesso (punto 1).', "es": 'Pega primero tu token de acceso (punto 1).', "de": 'Füge zuerst dein Zugriffstoken ein (Punkt 1).', "zh": '请先粘贴你的访问令牌（第 1 步）。', "nl": 'Plak eerst je toegangstoken (punt 1).', "fr": "Collez d'abord votre jeton d'accès (point 1).", "ja": '先にアクセストークンを貼り付けてください（手順 1）。', "vec": 'Incola prima el to token de acesso (punto 1).'},
    'pub.need_file': {"it": 'Scegli prima un file immagine.', "es": 'Elige primero un archivo de imagen.', "de": 'Wähle zuerst eine Bilddatei.', "zh": '请先选择一个图片文件。', "nl": 'Kies eerst een afbeeldingsbestand.', "fr": "Choisissez d'abord un fichier image.", "ja": '先に画像ファイルを選んでください。', "vec": 'Sielsi prima un file imàgine.'},
    'pub.uploading': {"it": 'Caricamento...', "es": 'Subiendo...', "de": 'Wird hochgeladen...', "zh": '正在上传...', "nl": 'Uploaden...', "fr": 'Téléversement...', "ja": 'アップロード中...', "vec": 'Cargamento...'},
    'pub.uploaded': {"it": 'Caricata:', "es": 'Subida:', "de": 'Hochgeladen:', "zh": '已上传：', "nl": 'Geüpload:', "fr": 'Téléversée :', "ja": 'アップロード完了：', "vec": 'Cargà:'},
    'pub.bad_token': {"it": 'Token non valido o scaduto.', "es": 'Token no válido o caducado.', "de": 'Token ungültig oder abgelaufen.', "zh": '令牌无效或已过期。', "nl": 'Token ongeldig of verlopen.', "fr": 'Jeton invalide ou expiré.', "ja": 'トークンが無効または期限切れです。', "vec": 'Token no vàlido o scadù.'},
    'pub.bad_token_relogin': {"it": 'Token non valido o scaduto. Rifai il login e incolla il token.', "es": 'Token no válido o caducado. Vuelve a iniciar sesión y pega el token.', "de": 'Token ungültig oder abgelaufen. Melde dich erneut an und füge den Token ein.', "zh": '令牌无效或已过期。请重新登录并粘贴令牌。', "nl": 'Token ongeldig of verlopen. Log opnieuw in en plak het token.', "fr": 'Jeton invalide ou expiré. Reconnectez-vous et collez le jeton.', "ja": 'トークンが無効または期限切れです。再ログインしてトークンを貼り付けてください。', "vec": 'Token no vàlido o scadù. Torna a far login e incola el token.'},
    'pub.upload_failed': {"it": 'Upload fallito', "es": 'Subida fallida', "de": 'Upload fehlgeschlagen', "zh": '上传失败', "nl": 'Upload mislukt', "fr": 'Échec du téléversement', "ja": 'アップロード失敗', "vec": 'Upload falìo'},
    'pub.bad_cicheto': {"it": 'Cicheto non valido:', "es": 'Cichéto no válido:', "de": 'Cichéto ungültig:', "zh": 'cichéto 无效：', "nl": 'Cichéto ongeldig:', "fr": 'Cichéto invalide :', "ja": 'cichéto が無効です：', "vec": 'Cicheto no vàlido:'},
    'pub.throttled': {"it": 'Troppe richieste, riprova tra poco.', "es": 'Demasiadas peticiones, inténtalo de nuevo pronto.', "de": 'Zu viele Anfragen, versuche es bald erneut.', "zh": '请求过多，请稍后再试。', "nl": 'Te veel verzoeken, probeer het straks opnieuw.', "fr": 'Trop de requêtes, réessayez bientôt.', "ja": 'リクエストが多すぎます。しばらくして再試行してください。', "vec": 'Massa richieste, riprova tra un poco.'},
    'pub.error': {"it": 'Errore', "es": 'Error', "de": 'Fehler', "zh": '错误', "nl": 'Fout', "fr": 'Erreur', "ja": 'エラー', "vec": 'Eror'},
    # --- privacy notice (GDPR arts. 13-14) ---
    'privacy.title': {"it": 'Informativa privacy', "es": 'Política de privacidad', "de": 'Datenschutzerklärung', "zh": '隐私声明', "nl": 'Privacyverklaring', "fr": 'Politique de confidentialité', "ja": 'プライバシーに関する通知', "vec": 'Informativa privacy'},
    'privacy.intro': {"it": 'spritz raccoglie il minimo indispensabile per farti accedere e ricordare le app che hai aggiunto alla tua libreria. Questa pagina spiega cosa conserviamo, perché, e come esercitare i tuoi diritti.', "es": 'spritz recopila lo mínimo necesario para que accedas y recordar las apps que has añadido a tu biblioteca. Esta página explica qué guardamos, por qué y cómo ejercer tus derechos.', "de": 'spritz erhebt nur das Nötigste, damit du dich anmelden kannst und wir die zu deiner Bibliothek hinzugefügten Apps merken. Diese Seite erklärt, was wir speichern, warum und wie du deine Rechte ausübst.', "zh": 'spritz 仅收集让你登录并记住你添加到库中的应用所必需的最少信息。本页说明我们保存什么、为何保存以及如何行使你的权利。', "nl": 'spritz verzamelt het minimum dat nodig is om je te laten inloggen en de apps te onthouden die je aan je bibliotheek hebt toegevoegd. Deze pagina legt uit wat we bewaren, waarom en hoe je je rechten uitoefent.', "fr": "spritz ne collecte que le strict nécessaire pour vous connecter et retenir les apps ajoutées à votre bibliothèque. Cette page explique ce que nous conservons, pourquoi, et comment exercer vos droits.", "ja": 'spritz は、ログインとライブラリに追加したアプリを記憶するために必要な最小限の情報のみを収集します。このページでは、保存する内容、その理由、および権利の行使方法を説明します。', "vec": 'spritz raccoglie el minimo indispensabile par farte entrar e ricordar le app che ti gà zontà a la to libraria. Sta pagina spiega cosa tegnemo, parché, e come exercitar i to diriti.'},
    'privacy.data_title': {"it": 'Dati che conserviamo', "es": 'Datos que guardamos', "de": 'Welche Daten wir speichern', "zh": '我们保存的数据', "nl": 'Gegevens die we bewaren', "fr": 'Données que nous conservons', "ja": '保存するデータ', "vec": 'Dati che tegnemo'},
    'privacy.data_email': {"it": 'La tua email e una password cifrata (hash bcrypt, mai in chiaro). Servono per l\'accesso.', "es": 'Tu email y una contraseña cifrada (hash bcrypt, nunca en claro). Se usan para el acceso.', "de": 'Deine E-Mail und ein gehashtes Passwort (bcrypt, nie im Klartext). Für die Anmeldung.', "zh": '你的电子邮件和加密后的密码（bcrypt 哈希，绝不明文存储）。用于登录。', "nl": 'Je e-mail en een gehasht wachtwoord (bcrypt, nooit leesbaar). Voor het inloggen.', "fr": "Votre email et un mot de passe haché (bcrypt, jamais en clair). Pour la connexion.", "ja": 'メールアドレスとハッシュ化されたパスワード（bcrypt、平文では保存しません）。ログインに使用します。', "vec": 'La to email e na password cifrà (hash bcrypt, mai in ciaro). Le serve par entrar.'},
    'privacy.data_library': {"it": 'La lista delle app che aggiungi alla libreria (id app, canale, architettura, stato). Serve a sincronizzare le installazioni.', "es": 'La lista de apps que añades a la biblioteca (id de app, canal, arquitectura, estado). Para sincronizar las instalaciones.', "de": 'Die Liste der zu deiner Bibliothek hinzugefügten Apps (App-ID, Kanal, Architektur, Status). Zur Synchronisierung der Installationen.', "zh": '你添加到库中的应用列表（应用 ID、通道、架构、状态）。用于同步安装。', "nl": 'De lijst met apps die je aan je bibliotheek toevoegt (app-id, kanaal, architectuur, status). Om installaties te synchroniseren.', "fr": "La liste des apps ajoutées à votre bibliothèque (id app, canal, architecture, état). Pour synchroniser les installations.", "ja": 'ライブラリに追加したアプリのリスト（アプリ ID、チャンネル、アーキテクチャ、状態）。インストールの同期に使用します。', "vec": 'La lista de le app che ti zonti a la libraria (id app, canal, architetura, stato). La serve a sincronizar le instalazion.'},
    'privacy.data_none': {"it": 'Non usiamo cookie di tracciamento, non profiliamo, non vendiamo dati. Le statistiche di download sono anonime (nessun id utente, nessun IP). Il tuo indirizzo IP è usato solo momentaneamente per limitare gli abusi e non viene memorizzato.', "es": 'No usamos cookies de rastreo, no perfilamos, no vendemos datos. Las estadísticas de descarga son anónimas (sin id de usuario, sin IP). Tu IP se usa solo momentáneamente para limitar abusos y no se almacena.', "de": 'Wir verwenden keine Tracking-Cookies, erstellen keine Profile, verkaufen keine Daten. Download-Statistiken sind anonym (keine Nutzer-ID, keine IP). Deine IP wird nur kurzzeitig zur Missbrauchsbegrenzung genutzt und nicht gespeichert.', "zh": '我们不使用跟踪 cookie，不进行画像，不出售数据。下载统计是匿名的（无用户 ID，无 IP）。你的 IP 仅短暂用于限制滥用，不会被存储。', "nl": 'We gebruiken geen tracking-cookies, maken geen profielen, verkopen geen gegevens. Downloadstatistieken zijn anoniem (geen gebruikers-id, geen IP). Je IP wordt alleen kortstondig gebruikt om misbruik te beperken en niet opgeslagen.', "fr": "Nous n'utilisons pas de cookies de suivi, ne profilons pas, ne vendons pas de données. Les statistiques de téléchargement sont anonymes (pas d'id utilisateur, pas d'IP). Votre IP n'est utilisée que momentanément pour limiter les abus et n'est pas conservée.", "ja": 'トラッキング Cookie は使用せず、プロファイリングもデータの販売も行いません。ダウンロード統計は匿名です（ユーザー ID なし、IP なし）。IP は不正利用を制限するために一時的に使うだけで保存しません。', "vec": 'No dopramo cookie de tracciamento, no profilamo, no vendemo dati. Le statistiche de download xe anonime (nissun id utente, nissun IP). El to IP xe doprà solo par un momento par limitar i abusi e no vien memorizà.'},
    'privacy.basis_title': {"it": 'Base giuridica e conservazione', "es": 'Base jurídica y conservación', "de": 'Rechtsgrundlage und Aufbewahrung', "zh": '法律依据与保存', "nl": 'Rechtsgrondslag en bewaring', "fr": 'Base juridique et conservation', "ja": '法的根拠と保存', "vec": 'Base giuridica e conservazion'},
    'privacy.basis_text': {"it": 'Trattiamo questi dati per eseguire il servizio che ci chiedi (art. 6.1.b GDPR). Li conserviamo finché tieni attivo l\'account: quando lo elimini, cancelliamo email, password e libreria.', "es": 'Tratamos estos datos para ejecutar el servicio que nos pides (art. 6.1.b RGPD). Los conservamos mientras mantengas la cuenta: al eliminarla, borramos email, contraseña y biblioteca.', "de": 'Wir verarbeiten diese Daten zur Erbringung des von dir angeforderten Dienstes (Art. 6.1.b DSGVO). Wir bewahren sie auf, solange dein Konto besteht: Löschst du es, entfernen wir E-Mail, Passwort und Bibliothek.', "zh": '我们处理这些数据是为了提供你请求的服务（GDPR 第 6.1.b 条）。只要你保留账户我们就会保存；删除账户时，我们会删除电子邮件、密码和库。', "nl": 'We verwerken deze gegevens om de door jou gevraagde dienst te leveren (art. 6.1.b AVG). We bewaren ze zolang je account bestaat: bij verwijdering wissen we e-mail, wachtwoord en bibliotheek.', "fr": "Nous traitons ces données pour exécuter le service que vous demandez (art. 6.1.b RGPD). Nous les conservons tant que votre compte existe : à sa suppression, nous effaçons email, mot de passe et bibliothèque.", "ja": 'これらのデータは、お客様が要求するサービスを提供するために処理します（GDPR 第 6.1.b 条）。アカウントがある限り保存し、削除時にメール、パスワード、ライブラリを消去します。', "vec": 'Tratemo sti dati par far el servizio che ti ne domandi (art. 6.1.b GDPR). Li tegnemo fin che ti tien l\'account: quando lo elimini, canceleremo email, password e libraria.'},
    'privacy.rights_title': {"it": 'I tuoi diritti', "es": 'Tus derechos', "de": 'Deine Rechte', "zh": '你的权利', "nl": 'Je rechten', "fr": 'Vos droits', "ja": 'あなたの権利', "vec": 'I to diriti'},
    'privacy.rights_access': {"it": 'Accesso e portabilità: scarica tutti i tuoi dati in formato JSON con una chiamata a /auth/me (autenticata).', "es": 'Acceso y portabilidad: descarga todos tus datos en JSON con una llamada a /auth/me (autenticada).', "de": 'Auskunft und Übertragbarkeit: Lade all deine Daten als JSON über /auth/me (authentifiziert) herunter.', "zh": '访问与可携带性：通过（已认证的）/auth/me 调用以 JSON 下载你的全部数据。', "nl": 'Toegang en overdraagbaarheid: download al je gegevens als JSON via een (geauthenticeerde) aanroep van /auth/me.', "fr": "Accès et portabilité : téléchargez toutes vos données en JSON via un appel (authentifié) à /auth/me.", "ja": 'アクセスとポータビリティ：（認証済みの）/auth/me 呼び出しで全データを JSON でダウンロードできます。', "vec": 'Acesso e portabilità: scarga tuti i to dati in JSON con na ciamada a /auth/me (autenticà).'},
    'privacy.rights_erase': {"it": 'Cancellazione: elimina definitivamente il tuo account e tutti i dati dalla pagina "I miei dati", oppure con /auth/delete-account.', "es": 'Supresión: elimina definitivamente tu cuenta y todos los datos desde la página "Mis datos", o con /auth/delete-account.', "de": 'Löschung: Entferne dein Konto und alle Daten endgültig über die Seite „Meine Daten" oder mit /auth/delete-account.', "zh": '删除：从"我的数据"页面或通过 /auth/delete-account 永久删除你的账户及所有数据。', "nl": 'Verwijdering: verwijder je account en alle gegevens definitief via de pagina "Mijn gegevens" of met /auth/delete-account.', "fr": 'Effacement : supprimez définitivement votre compte et toutes vos données depuis la page « Mes données » ou via /auth/delete-account.', "ja": '削除：「マイデータ」ページまたは /auth/delete-account でアカウントと全データを完全に削除できます。', "vec": 'Cancelazion: elimina par senpre el to account e tuti i dati da la pagina "I me dati", o con /auth/delete-account.'},
    'privacy.contact': {"it": 'Il titolare del trattamento è Andrea Bernardi. Per esercitare i tuoi diritti o per qualsiasi domanda sul trattamento dei dati, scrivi a andrea@studiobernardi.eu.', "es": 'El responsable del tratamiento es Andrea Bernardi. Para ejercer tus derechos o cualquier duda sobre el tratamiento de datos, escribe a andrea@studiobernardi.eu.', "de": 'Verantwortlicher für die Verarbeitung ist Andrea Bernardi. Um deine Rechte auszuüben oder bei Fragen zur Datenverarbeitung, schreibe an andrea@studiobernardi.eu.', "zh": '数据控制者为 Andrea Bernardi。如需行使权利或对数据处理有任何疑问，请发送邮件至 andrea@studiobernardi.eu。', "nl": 'De verwerkingsverantwoordelijke is Andrea Bernardi. Om je rechten uit te oefenen of bij vragen over de gegevensverwerking, mail naar andrea@studiobernardi.eu.', "fr": "Le responsable du traitement est Andrea Bernardi. Pour exercer vos droits ou toute question sur le traitement des données, écrivez à andrea@studiobernardi.eu.", "ja": 'データ管理者は Andrea Bernardi です。権利の行使やデータ処理に関するご質問は、andrea@studiobernardi.eu までご連絡ください。', "vec": 'El titolar del tratamento xe Andrea Bernardi. Par exercitar i to diriti o par qualsiasi domanda sul tratamento dei dati, scrivi a andrea@studiobernardi.eu.'},
    'privacy.link': {"it": 'Privacy', "es": 'Privacidad', "de": 'Datenschutz', "zh": '隐私', "nl": 'Privacy', "fr": 'Confidentialité', "ja": 'プライバシー', "vec": 'Privacy'},
    # --- account page (my data / erasure) ---
    'account.title': {"it": 'I miei dati', "es": 'Mis datos', "de": 'Meine Daten', "zh": '我的数据', "nl": 'Mijn gegevens', "fr": 'Mes données', "ja": 'マイデータ', "vec": 'I me dati'},
    'account.lead': {"it": 'Vedi cosa spritz conserva su di te ed esercita i tuoi diritti.', "es": 'Consulta qué guarda spritz sobre ti y ejerce tus derechos.', "de": 'Sieh, was spritz über dich speichert, und übe deine Rechte aus.', "zh": '查看 spritz 保存了你的哪些信息并行使你的权利。', "nl": 'Bekijk wat spritz over je bewaart en oefen je rechten uit.', "fr": 'Voyez ce que spritz conserve sur vous et exercez vos droits.', "ja": 'spritz が保存しているあなたの情報を確認し、権利を行使できます。', "vec": 'Varda cosa spritz tien su de ti e exercita i to diriti.'},
    'account.export': {"it": 'Scarica i miei dati (JSON)', "es": 'Descargar mis datos (JSON)', "de": 'Meine Daten herunterladen (JSON)', "zh": '下载我的数据 (JSON)', "nl": 'Mijn gegevens downloaden (JSON)', "fr": 'Télécharger mes données (JSON)', "ja": 'マイデータをダウンロード (JSON)', "vec": 'Scarga i me dati (JSON)'},
    'account.delete_title': {"it": 'Elimina account', "es": 'Eliminar cuenta', "de": 'Konto löschen', "zh": '删除账户', "nl": 'Account verwijderen', "fr": 'Supprimer le compte', "ja": 'アカウントを削除', "vec": 'Elimina account'},
    'account.delete_warn': {"it": 'Questa azione è irreversibile: elimina email, password e libreria. Inserisci la password per confermare.', "es": 'Esta acción es irreversible: elimina email, contraseña y biblioteca. Introduce la contraseña para confirmar.', "de": 'Diese Aktion ist unwiderruflich: E-Mail, Passwort und Bibliothek werden gelöscht. Gib zur Bestätigung dein Passwort ein.', "zh": '此操作不可撤销：将删除电子邮件、密码和库。请输入密码以确认。', "nl": 'Deze actie is onomkeerbaar: e-mail, wachtwoord en bibliotheek worden verwijderd. Voer je wachtwoord in ter bevestiging.', "fr": 'Cette action est irréversible : email, mot de passe et bibliothèque seront supprimés. Saisissez le mot de passe pour confirmer.', "ja": 'この操作は取り消せません。メール、パスワード、ライブラリを削除します。確認のためパスワードを入力してください。', "vec": 'Sta azion no se pol tornar indrio: la elimina email, password e libraria. Meti la password par confermar.'},
    'account.delete_btn': {"it": 'Elimina definitivamente', "es": 'Eliminar definitivamente', "de": 'Endgültig löschen', "zh": '永久删除', "nl": 'Definitief verwijderen', "fr": 'Supprimer définitivement', "ja": '完全に削除', "vec": 'Elimina par senpre'},
    'account.deleted': {"it": 'Account eliminato. Arrivederci.', "es": 'Cuenta eliminada. Adiós.', "de": 'Konto gelöscht. Auf Wiedersehen.', "zh": '账户已删除。再见。', "nl": 'Account verwijderd. Tot ziens.', "fr": 'Compte supprimé. Au revoir.', "ja": 'アカウントを削除しました。さようなら。', "vec": 'Account eliminà. Ariveder.'},
    'account.need_login': {"it": 'Accedi per vedere i tuoi dati.', "es": 'Accede para ver tus datos.', "de": 'Melde dich an, um deine Daten zu sehen.', "zh": '请登录以查看你的数据。', "nl": 'Log in om je gegevens te zien.', "fr": 'Connectez-vous pour voir vos données.', "ja": 'データを表示するにはログインしてください。', "vec": 'Entra par védar i to dati.'},
    'account.wrong_pw': {"it": 'Password errata.', "es": 'Contraseña incorrecta.', "de": 'Falsches Passwort.', "zh": '密码错误。', "nl": 'Onjuist wachtwoord.', "fr": 'Mot de passe incorrect.', "ja": 'パスワードが違います。', "vec": 'Password sbaglià.'},
    'nav.account': {"it": 'I miei dati', "es": 'Mis datos', "de": 'Meine Daten', "zh": '我的数据', "nl": 'Mijn gegevens', "fr": 'Mes données', "ja": 'マイデータ', "vec": 'I me dati'},
}


def normalize_lang(value: str | None) -> str:
    """Map an arbitrary value (cookie or Accept-Language) to a supported code.

    Handles both 2-letter codes (it, de, ja) and longer ones (vec). Tries the
    full token first, then its 2-letter prefix (so "it-IT" -> "it")."""
    if not value:
        return DEFAULT_LANG
    code = value.strip().lower()
    # drop a region/quality suffix like "it-IT" or "en;q=0.8" for the prefix try
    base = code.split("-")[0].split(";")[0]
    if code in LANGS:
        return code
    if base in LANGS:
        return base
    return DEFAULT_LANG


def t(key: str, lang: str = DEFAULT_LANG, **fmt) -> str:
    """Translate `key` into `lang`, falling back to Italian then the key itself.
    Supports {placeholder} formatting via kwargs."""
    entry = STRINGS.get(key)
    if not entry:
        return key
    text = entry.get(lang) or entry.get(DEFAULT_LANG) or key
    if fmt:
        try:
            return text.format(**fmt)
        except (KeyError, IndexError):
            return text
    return text
