"""Repo-proxy layer: serve a HaikuDepot-compatible repository.

This is the task 01 piece. A standard Haiku repository is a fixed layout under
one baseUrl:

    <baseUrl>/repo.info                  text: name, vendor, architecture, url...
    <baseUrl>/repo                       HPKR binary catalog (built by package_repo)
    <baseUrl>/packages/<filename>.hpkg   the package files

HaikuDepot reads repo.info + the HPKR catalog, then fetches each package from
`baseUrl + filename`. It cannot follow arbitrary per-package URLs, so spritz
must serve the bytes under its own baseUrl. We do it as an on-demand proxy:
fetch the author's hpkg on first request, verify sha256, cache to disk, serve.

Two hard constraints from the spike (see docs/DECISIONS.md):
  - package_repo enforces a strict vendor-match: every package in a repo must
    share the repo's vendor. So we group packages by (vendor, arch), one
    sub-repo each. The vendor is read from the hpkg's own .PackageInfo, not the
    cichéto (the cichéto has no vendor field; the author chose it inside the hpkg).
  - The catalog is HPKR, a Haiku binary format, generated by the host-built
    `package_repo` tool (config.PACKAGE_REPO_BIN). If that tool is absent the
    layer degrades to 503 rather than taking the whole server down.
"""
from __future__ import annotations

import hashlib
import os
import re
import shutil
import subprocess
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

import httpx

from . import config, netguard


class RepoProxyError(RuntimeError):
    """Anything that should surface as a clean error to the caller."""


class ToolUnavailable(RepoProxyError):
    """package_repo is not configured / not found."""


# ---------- the package_repo tool ----------

def _tool_path() -> str:
    bin_path = config.PACKAGE_REPO_BIN
    if not bin_path or not Path(bin_path).is_file():
        raise ToolUnavailable(
            "package_repo is not available; set SPRITZ_PACKAGE_REPO_BIN to the "
            "host-built tool (see docs/SETUP-WSL.md step 2)"
        )
    return bin_path


def _tool_env() -> dict:
    """package_repo needs its sibling libbe_build.so etc. on the library path.

    By convention the shared libs live two levels up from the tool, under
    .../linux/lib. We add that automatically; callers can still override with
    LD_LIBRARY_PATH in the environment.
    """
    env = dict(os.environ)
    tool = Path(_tool_path()).resolve()
    # .../linux/x86_64/release/tools/package_repo/package_repo -> .../linux/lib
    for parent in tool.parents:
        cand = parent / "lib"
        if (cand / "libpackage_build.so").is_file():
            existing = env.get("LD_LIBRARY_PATH", "")
            env["LD_LIBRARY_PATH"] = f"{cand}:{existing}" if existing else str(cand)
            break
    return env


def tool_available() -> bool:
    try:
        _tool_path()
        return True
    except ToolUnavailable:
        return False


# ---------- reading an hpkg's own metadata ----------

@dataclass
class PackageMeta:
    name: str
    version: str
    architecture: str
    vendor: str


_META_LINE = re.compile(r"^\s*(name|version|architecture|vendor):\s*(.+?)\s*$")


def read_package_meta(hpkg: Path) -> PackageMeta:
    """Read name/version/arch/vendor from an hpkg's .PackageInfo.

    Uses `package list -i`. Requires the `package` tool to sit next to
    package_repo (same build output); we derive its path from PACKAGE_REPO_BIN.
    """
    pkg_tool = Path(_tool_path()).parent.parent / "package" / "package"
    if not pkg_tool.is_file():
        raise ToolUnavailable(f"`package` tool not found next to package_repo at {pkg_tool}")
    out = subprocess.run(
        [str(pkg_tool), "list", "-i", str(hpkg)],
        env=_tool_env(), capture_output=True, text=True, check=True,
    ).stdout
    fields: dict[str, str] = {}
    for line in out.splitlines():
        m = _META_LINE.match(line)
        if m:
            fields.setdefault(m.group(1), m.group(2))
    missing = {"name", "version", "architecture", "vendor"} - fields.keys()
    if missing:
        raise RepoProxyError(f"hpkg {hpkg.name} is missing .PackageInfo fields: {missing}")
    return PackageMeta(fields["name"], fields["version"],
                       fields["architecture"], fields["vendor"])


def canonical_filename(meta: PackageMeta) -> str:
    """The filename HaikuDepot expects: name-version-arch.hpkg. This must match
    what the HPKR catalog records, so the package fetch resolves."""
    return f"{meta.name}-{meta.version}-{meta.architecture}.hpkg"


# ---------- on-demand proxy fetch ----------

def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


# Cap on a single downloaded artifact, to bound disk and a hostile server.
MAX_ARTIFACT_BYTES = 500 * 1024 * 1024  # 500 MB


def _guard_fetch_url(url: str) -> None:
    """SSRF guard for author URLs (shared netguard); maps to RepoProxyError."""
    try:
        netguard.guard_url(url)
    except netguard.BlockedURLError as e:
        raise RepoProxyError(str(e)) from e


def fetch_verified(url: str, sha256: Optional[str], dest: Path) -> Path:
    """Download `url` to `dest`, verifying sha256 if given. Cached: if dest
    already exists and (when a hash is given) matches, reuse it.

    On hash mismatch the partial file is removed and an error is raised, loudly.
    A missing sha256 is allowed only for unpinned channels; the caller decides.
    The URL is SSRF-guarded and the download is size-capped.
    """
    if dest.exists() and sha256 and _sha256_file(dest) == sha256.lower():
        return dest

    _guard_fetch_url(url)
    dest.parent.mkdir(parents=True, exist_ok=True)
    tmp = dest.with_suffix(dest.suffix + ".part")
    try:
        with httpx.stream("GET", url, follow_redirects=True, timeout=60.0) as r:
            r.raise_for_status()
            written = 0
            with tmp.open("wb") as f:
                for chunk in r.iter_bytes(1 << 20):
                    written += len(chunk)
                    if written > MAX_ARTIFACT_BYTES:
                        raise RepoProxyError(
                            f"artifact exceeds {MAX_ARTIFACT_BYTES} bytes: {url}"
                        )
                    f.write(chunk)
    except httpx.HTTPError as e:
        tmp.unlink(missing_ok=True)
        raise RepoProxyError(f"failed to fetch {url}: {e}") from e
    except RepoProxyError:
        tmp.unlink(missing_ok=True)
        raise

    if sha256:
        got = _sha256_file(tmp)
        if got != sha256.lower():
            tmp.unlink(missing_ok=True)
            raise RepoProxyError(
                f"sha256 mismatch for {url}: expected {sha256.lower()}, got {got}"
            )
    tmp.replace(dest)
    return dest


# ---------- building a sub-repo ----------

def _repo_info_text(name: str, vendor: str, architecture: str,
                    identifier: str, base_url: str,
                    summary: str = "spritz repository", priority: int = 1) -> str:
    """repo.info is a driver-settings-style text file. Field names per Haiku's
    parser (RepositoryInfo.cpp): `identifier` is the stable repo identity (the
    legacy key for it is `url`), `baseurl` is where packages are fetched from.
    Both name and identifier are required."""
    return (
        f'name\t\t\t{name}\n'
        f'vendor\t\t\t"{vendor}"\n'
        f'summary\t\t\t"{summary}"\n'
        f'priority\t\t{priority}\n'
        f'identifier\t\t"{identifier}"\n'
        f'baseurl\t\t\t"{base_url}"\n'
        f'architecture\t{architecture}\n'
    )


def stable_identifier(out_dir: Path) -> str:
    """Return this sub-repo's identifier UUID, generating and persisting it once.

    The identifier MUST stay constant across rebuilds and mirrors (HaikuDepot
    keys the repo by it), so we store it in `identifier` next to the sub-repo and
    reuse it forever after.
    """
    id_file = out_dir / "identifier"
    if id_file.is_file():
        existing = id_file.read_text().strip()
        if existing:
            return existing
    out_dir.mkdir(parents=True, exist_ok=True)
    new_id = str(uuid.uuid4())
    id_file.write_text(new_id + "\n")
    return new_id


def build_subrepo(hpkgs: list[Path], vendor: str, architecture: str,
                  out_dir: Path, base_url: str) -> Path:
    """Generate repo.info + the HPKR catalog for one (vendor, arch).

    Lays out out_dir as the served baseUrl directory:
        out_dir/repo.info
        out_dir/repo               (HPKR catalog)
        out_dir/packages/<file>    (the hpkg, hardlinked/copied in)
        out_dir/identifier         (persisted stable UUID, not served)

    Raises if package_repo rejects the set (e.g. a vendor mismatch slipped in).
    """
    tool = _tool_path()
    out_dir.mkdir(parents=True, exist_ok=True)
    pkg_dir = out_dir / "packages"
    pkg_dir.mkdir(exist_ok=True)

    # repo.info: a stable, filesystem-safe repo name + a persistent identifier.
    repo_name = re.sub(r"[^A-Za-z0-9_]+", "-", f"{vendor}-{architecture}").strip("-").lower()
    identifier = stable_identifier(out_dir)
    info_path = out_dir / "repo.info"
    info_path.write_text(
        _repo_info_text(repo_name, vendor, architecture, identifier, base_url)
    )

    # Stage packages under packages/ with their canonical filenames, the names
    # the HPKR catalog will record (name-version-arch.hpkg), so fetches resolve.
    staged: list[Path] = []
    for h in hpkgs:
        target = pkg_dir / canonical_filename(read_package_meta(h))
        if target.resolve() != h.resolve():
            shutil.copy2(h, target)
        staged.append(target)

    # `package_repo create <repo-info> <package...>` writes a file named "repo"
    # next to the repo.info it was given (not into the cwd, and there is no
    # output-path flag). Since repo.info already lives in out_dir, the catalog
    # lands at out_dir/repo, exactly where we serve it from.
    cmd = [tool, "create", str(info_path.resolve()),
           *[str(p.resolve()) for p in staged]]
    proc = subprocess.run(cmd, env=_tool_env(), capture_output=True, text=True)
    if proc.returncode != 0:
        raise RepoProxyError(
            "package_repo create failed (vendor mismatch or bad hpkg):\n"
            + (proc.stderr or proc.stdout)
        )
    catalog = out_dir / "repo"
    if not catalog.is_file():
        raise RepoProxyError("package_repo create produced no catalog")
    return out_dir
