"""initial schema

Revision ID: 126d255d8b9c
Revises: 
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '126d255d8b9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bacari',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('git_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('last_ingested', sa.Integer(), nullable=False),
    sa.Column('last_removed', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('cicheti',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bacaro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('categories', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('haikuports', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('channels', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cicheti', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cicheti_bacaro'), ['bacaro'], unique=False)
        batch_op.create_index(batch_op.f('ix_cicheti_name'), ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cicheto_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_library_cicheto_id'), ['cicheto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_state'), ['state'], unique=False)
        batch_op.create_index(batch_op.f('ix_library_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('library', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_library_user_id'))
        batch_op.drop_index(batch_op.f('ix_library_state'))
        batch_op.drop_index(batch_op.f('ix_library_cicheto_id'))

    op.drop_table('library')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('cicheti', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cicheti_name'))
        batch_op.drop_index(batch_op.f('ix_cicheti_bacaro'))

    op.drop_table('cicheti')
    op.drop_table('bacari')
    # ### end Alembic commands ###
